name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: medaminecheikh 
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .github Directory
        run: mkdir -p .github

      - name: Move Snake File
        run: mv dist/github-contribution-grid-snake.svg .github/contribution-snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/contribution-snake.svg
          git commit -m "Generated contribution snake"
          git push
